// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.item.test.dubbo.demo;

public interface DemoReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Demo.DemoReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
