// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.item.test.dubbo.demo;

public final class DemoProto {
  private DemoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Demo_DemoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Demo_DemoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Demo_DemoReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Demo_DemoReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Demo_PersonTest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Demo_PersonTest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Demo_PersonTest_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Demo_PersonTest_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Demo_PersonTest_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Demo_PersonTest_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ndemo.proto\022\004Demo\"\033\n\013DemoRequest\022\014\n\004nam" +
      "e\030\001 \001(\t\"\034\n\tDemoReply\022\017\n\007message\030\001 \001(\t\"\211\003" +
      "\n\nPersonTest\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r" +
      "\n\005email\030\003 \001(\t\022!\n\003sex\030\004 \001(\0162\024.Demo.Person" +
      "Test.Sex\022+\n\005phone\030\005 \003(\0132\034.Demo.PersonTes" +
      "t.PhoneNumber\022(\n\004tags\030\006 \003(\0132\032.Demo.Perso" +
      "nTest.TagsEntry\032+\n\tTagsEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\t:\0028\001\032\200\001\n\013PhoneNumber\022\016\n\006" +
      "number\030\001 \001(\t\0224\n\004type\030\002 \001(\0162&.Demo.Person" +
      "Test.PhoneNumber.PhoneType\"+\n\tPhoneType\022" +
      "\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002\"(\n\003Sex\022\013" +
      "\n\007DEFAULT\020\000\022\010\n\004MALE\020\001\022\n\n\006Female\020\002B-\n\030com" +
      ".item.test.dubbo.demoB\tDemoProtoP\001\242\002\003HLW" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Demo_DemoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Demo_DemoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Demo_DemoRequest_descriptor,
        new String[] { "Name", });
    internal_static_Demo_DemoReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Demo_DemoReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Demo_DemoReply_descriptor,
        new String[] { "Message", });
    internal_static_Demo_PersonTest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Demo_PersonTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Demo_PersonTest_descriptor,
        new String[] { "Id", "Name", "Email", "Sex", "Phone", "Tags", });
    internal_static_Demo_PersonTest_TagsEntry_descriptor =
      internal_static_Demo_PersonTest_descriptor.getNestedTypes().get(0);
    internal_static_Demo_PersonTest_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Demo_PersonTest_TagsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_Demo_PersonTest_PhoneNumber_descriptor =
      internal_static_Demo_PersonTest_descriptor.getNestedTypes().get(1);
    internal_static_Demo_PersonTest_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Demo_PersonTest_PhoneNumber_descriptor,
        new String[] { "Number", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
