// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.item.test.dubbo.demo;

public interface PersonTestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Demo.PersonTest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * int 类型
   * </pre>
   *
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <pre>
   * string 类型
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  String getName();
  /**
   * <pre>
   * string 类型
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <pre>
   * 枚举类型
   * </pre>
   *
   * <code>.Demo.PersonTest.Sex sex = 4;</code>
   * @return The enum numeric value on the wire for sex.
   */
  int getSexValue();
  /**
   * <pre>
   * 枚举类型
   * </pre>
   *
   * <code>.Demo.PersonTest.Sex sex = 4;</code>
   * @return The sex.
   */
  PersonTest.Sex getSex();

  /**
   * <pre>
   * 引用下面定义的 PhoneNumber 类型的 message
   * </pre>
   *
   * <code>repeated .Demo.PersonTest.PhoneNumber phone = 5;</code>
   */
  java.util.List<PersonTest.PhoneNumber>
      getPhoneList();
  /**
   * <pre>
   * 引用下面定义的 PhoneNumber 类型的 message
   * </pre>
   *
   * <code>repeated .Demo.PersonTest.PhoneNumber phone = 5;</code>
   */
  PersonTest.PhoneNumber getPhone(int index);
  /**
   * <pre>
   * 引用下面定义的 PhoneNumber 类型的 message
   * </pre>
   *
   * <code>repeated .Demo.PersonTest.PhoneNumber phone = 5;</code>
   */
  int getPhoneCount();
  /**
   * <pre>
   * 引用下面定义的 PhoneNumber 类型的 message
   * </pre>
   *
   * <code>repeated .Demo.PersonTest.PhoneNumber phone = 5;</code>
   */
  java.util.List<? extends PersonTest.PhoneNumberOrBuilder>
      getPhoneOrBuilderList();
  /**
   * <pre>
   * 引用下面定义的 PhoneNumber 类型的 message
   * </pre>
   *
   * <code>repeated .Demo.PersonTest.PhoneNumber phone = 5;</code>
   */
  PersonTest.PhoneNumberOrBuilder getPhoneOrBuilder(
      int index);

  /**
   * <pre>
   * map 类型
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */
  int getTagsCount();
  /**
   * <pre>
   * map 类型
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */
  boolean containsTags(
      String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getTags();
  /**
   * <pre>
   * map 类型
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */
  java.util.Map<String, String>
  getTagsMap();
  /**
   * <pre>
   * map 类型
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */

  String getTagsOrDefault(
      String key,
      String defaultValue);
  /**
   * <pre>
   * map 类型
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */

  String getTagsOrThrow(
      String key);
}
